### ISSUE TITLE
IE10 / 11 / Edge 20 bug with img padding, parts of colored image visible as background

### ISSUE THREAD

**Issue by ghost** [karlhorky/gray#44]
If a simple &lt;img&gt; has a padding in IE11/Win7, the image becomes gray but the colored version of the image is partially visible in the padding area "behind" the gray image.

IE11 bug: http://jsfiddle.net/41weta35/

IE11 (ugly and bad) workaround: http://jsfiddle.net/41weta35/1/

Thanks for the great project.

Also in this example: A colored border stays colored with IE11 and becomes gray with FF.

**Comment by karlhorky** [comment]
Sorry for the long wait on this, I'll be taking a look at issues again soon.

**Comment by karlhorky** [comment]
And thanks for the bug report.

**Comment by karlhorky** [comment]
Fixed in `1.4.3`

**Comment by ghost** [comment]
Tried with 1.4.4, a new bug is there, now the image is too small. :-(

Testcase IE11: http://jsfiddle.net/41weta35/4/

Also in this example: The border is colored in IE11 while it is gray in FF.

**Comment by karlhorky** [comment]
Ah, you are correct, there is a bug with the size now: #48

As for the border color, I've [documented this inconsistency](https://github.com/karlhorky/gray#caveats). Workaround here: http://jsfiddle.net/karlhorky/nmtb6mk1/2/

**Comment by karlhorky** [comment]
Size issue is fixed in `1.4.5`.

**Comment by ghost** [comment]
Still getting wrong padding with IE11 latest / Win 7.

![gray-1 4 5-ie11](https://cloud.githubusercontent.com/assets/3855671/21737416/a9a7d878-d478-11e6-9898-93c9a2f43cd7.png)

Testcase IE11: http://jsfiddle.net/41weta35/8/

**Comment by karlhorky** [comment]
Thank you. Indeed it is still not working - my test on the demo website works, but it doesn't work in jsfiddle. Opening #67 to track this.

I've updated your demo with a `https` CDN url too: http://jsfiddle.net/41weta35/9/
